name: Create testbuild OSE
on:
  workflow_dispatch
jobs:
  build:
    name: Create testbuild OSE
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4

      - name: Prepare keystore
        run: echo ${{ secrets.android_keystore_base64 }} | base64 -d >$GITHUB_WORKSPACE/keystore.jks
        # run: echo ${{ secrets.android_keystore_base64 }} | base64 -d > ${{ github.workspace }}/keystore.jks

      - name: Build signed package for OSE
        run: ./gradlew app:assembleOseRelease
        env:
          ANDROID_KEYSTORE: ${{ github.workspace }}/keystore.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.android_keystore_password }}
          ANDROID_KEY_ALIAS: ${{ secrets.android_key_alias }}
          ANDROID_KEY_PASSWORD: ${{ secrets.android_key_password }}
          CROWDIN_API_KEY: ${{ secrets.crowdin_api_key }}
          GOOGLE_GEO_API_KEY: ${{ secrets.google_geo_api_key }}
          GH_CONTRIBUTORS_API_KEY: ${{ secrets.gh_contributors_api_key }}

      # - name: Collect build results JSON
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: "build-results"
      #     ## /home/runner/work/_temp/.gradle-actions/build-results/__run_2-1740245720837.json
      #     path: ${{ runner.temp }}/.gradle-actions/build-results
      #     retention-days: 5

      # - name: "Artifacts: All"
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: "all"
      #     path: app/build/outputs/apk/
      #     retention-days: 5

      - name: "Artifacts: Android APK"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "android-apk"
          path: |
            app/build/outputs/apk/ose/*/*.apk
          retention-days: 5
